name: Greeting from Mona for docs

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
  pull_request:
    branches: [master]
    paths:
      - 'docs/**'

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        if: github.ref_name != 'master'
        with:
          python-version: 3.8.8

      - name: Install dependencies
        if: github.ref_name != 'master'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run flake8
        if: github.ref_name != 'master'
        id: run_checks
        run: |
          make flake8

  my-deploy_docs:
    name: My Job for docs
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo Hi there! It\'s docs action! $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.