name: Greeting from Mona for docs

on:
  push:
    branches: [master]
    paths:
      - 'docs/**'
  pull_request:
    branches: [master]
    paths:
      - 'docs/**'

jobs:
  my-job:
    name: My Job for docs
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo Hi there! It\'s docs action! $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.